# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c29b3f2d436557a436019fa300696fb7114ac02a8a4bb89427f78022577fb80121715166dd818ef119049aae796b1463fae17b2c11d069f67d205ab9d233ecba

test:
  secret_key_base: 33a70311191951596bcad7cc3b9e3d0f3ad34c67a300f307aed5e0fd6d1e4ee12470730e1d8265fb018be5fe9b4535e5f46f55822a01dd32462f0fb2e35d7203

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
